name: Backend case - cov
on:
  workflow_call:

jobs:
  backend_case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
         bash scripts/backend_case.sh
         bash scripts/backend_cov_dump.sh
         bash scripts/backend_cov_upload.sh