name: Backend case - cov
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  stand_alone_env:
    needs: build
    uses: ./.github/workflows/stand_alone_env.yml

  backend_case:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: |
         bash scripts/backend_case.sh
         bash scripts/backend_cov_dump.sh
         bash scripts/backend_cov_upload.sh