name: It - cov
on:
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          bash scripts/it_cov.sh
          bash scripts/cov_dump.sh
          bash scripts/cov_upload.sh
