name: Ut - cov
on:
  workflow_call:

jobs:
  ut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          bash scripts/ut_cov.sh
          bash scripts/cov_dump.sh
          bash scripts/cov_upload.sh
