name: CI - Branch
on:
  push:
    branches-ignore: [master, release/**]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  backend-p0-p1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/backend_p0_p1.sh

  ui-automation:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/ui_automation.sh