name: CI - Master
on:
  push:
    branches: [master]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  ut:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/ut.sh

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/integration_test.sh

  backend-p0-p1:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 25
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/backend_p0_p1.sh

  performance:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/performance.sh