name: Code Coverage
on:
  workflow_run:
    workflows:
      - CI - Master
      - Playwright Tests - UI Automation
    types:
      - completed

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Download all coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifact
          path: ./coverage-files

      - name: Merge Coverage
        run: bash scripts/coverage.sh