name: Code Coverage
on:
  workflow_run:
    workflows:
      - CI - Master
      - Playwright Tests - UI Automation
    types:
      - completed

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: true
    steps:
      - run: bash scripts/coverage.sh