name: Playwright Tests - Online UI Automation

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨 3 点执行

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Playwright and init
        run: |
          npm init -y
          npm install -D playwright
          npx playwright install --with-deps
          npx playwright codegen https://example.com

      - name: Run Playwright tests
        run: |
          echo "You can place tests in 'tests/' folder and run them here"
          npx playwright test || echo "No tests found, skipping."

      - name: Upload Playwright HTML report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30